### PR TITLE
remove postinstall script

### PR DESCRIPTION
**Pull request by lukaszblacha**
From now on the installation from git repo instead of npm registry will have to be followed with build command

### CODE REVIEW

**Comment by dlmr** [comment]
Hello! 

What is the reason for the change, why do we need to remove it other than removing functionality that might not be that important? Because the `postinstall` should not run during a normal npm install.

**Comment by lukaszblacha** [comment]
I did not check why it happened, but It runs in my docker image build for some reason

**Comment by andreasrs** [comment]
@lukaszblacha we resolved this on Slack right, so you're cool with us closing this one?

**Comment by lukaszblacha** [comment]
yes, closing the issue

**Pull request closed without merging**
